### PR TITLE
Fix building curl-sys without zlib under MSVC.

### LINKED ISSUE #168: Building on MSVC compiler fails
```
thread 'main' panicked at 'fs::copy(libs.join("lib/libcurl_a.lib"), dst.join("lib/curl.lib")) return the error (os error 3)', build.rs:334
stack backtrace:
   0:  0x106a260 - std::panicking::default_hook::{{closure}}
                       at C:\projects\rust\src\libstd\panicking.rs:354
   1:  0x1069d7c - std::panicking::default_hook
                       at C:\projects\rust\src\libstd\panicking.rs:371
   2:  0x106a787 - std::panicking::rust_panic_with_hook
                       at C:\projects\rust\src\libstd\panicking.rs:549
   3:  0x106a647 - std::panicking::begin_panic<collections::string::String>
                       at C:\projects\rust\src\libstd\panicking.rs:511
   4:  0x106a587 - std::panicking::begin_panic_fmt
                       at C:\projects\rust\src\libstd\panicking.rs:495
   5:   0xfdc9ce - build_script_build::build_msvc
                       at c:\Windows\Temp\curl-sys\build.rs:334
   6:   0xfd796d - build_script_build::main
                       at c:\Windows\Temp\curl-sys\build.rs:72
   7:  0x106c0cb - panic_unwind::__rust_maybe_catch_panic
                       at C:\projects\rust\src\libpanic_unwind\lib.rs:98
   8:  0x106addd - std::rt::lang_start
                       at C:\projects\rust\src\libstd\rt.rs:51
   9:   0xfde821 - main
  10:  0x10725a3 - __scrt_common_main_seh
                       at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:253
  11: 0x74ec3379 - BaseThreadInitThunk
  12: 0x770e92e1 - __RtlUserThreadStart
```

```
curl-sys>ls curl\builds
libcurl-vc-x86-release-static-ipv6-sspi-winssl
libcurl-vc-x86-release-static-ipv6-sspi-winssl-obj-curl
libcurl-vc-x86-release-static-ipv6-sspi-winssl-obj-lib

curl-sys>ls curl\builds\libcurl-vc-x86-release-static-ipv6-sspi-winssl
bin  include  lib
```

~Apparently curl has changed the output directory name.~ This issue is unrelated to #152.

Update: No, this name is handled in build.rs. No idea why it fails then :(

### PR DESCRIPTION
**Pull request by pravic**
Fixes #168.

Tested by building git2 with `[replace]`d curl-sys.

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks for the PR! I'm not quite sure how this happened though, does this mean that you're overriding libz-sys's build script or otherwise providing it at a different location?

**Comment by pravic** [comment]
No.

But I have installed zlib in my Vcpkg repository, may be it has the influence?

There is some mess with vcpkg-rs currently (and with other crates under msvc), so I am not sure that my PR will work correctly on any configuration despite of it looks quiet clear.

**Comment by mcgoo** [comment]
@pravic, I don't think it's anything to do with the vcpkg support, but if you do not want any interaction with Vcpkg/vcpkg-rs, you can set `NO_VCPKG=1` in your environment to disable it completely.

**Comment by pravic** [comment]
@mcgoo Thanks, I didn't notice about NO_VCPKG.

**Comment by alexcrichton** [comment]
Oh I think that this may be a bug in the libz-sys crate actually. If we find the crate through vcpkg I think we'll also want to print out the root and include folders still, right?

**Comment by alexcrichton** [comment]
Closing due to inactivity for now

**Pull request closed without merging**
