### PR TITLE
Make response body optional

### PR DESCRIPTION
**Pull request by posix4e**
This is a first stab at https://github.com/carllerche/curl-rust/issues/5. I'm curious what methods can have optional body. Should we set it to None automatically if response is set to 0?

### CODE REVIEW

**Comment by posix4e** [comment]
updated this pull request to remove the file I inadvertently added

**Comment by carllerche** [comment]
A good start. I was hoping to have the body be set to `None` when the response doesn't actually contain a response body (like the response to a `HEAD` request).

**Comment by posix4e** [comment]
Check the head test and tell me if that's what you are thinking.

**Comment by posix4e** [comment]
OK updated the patch again. I can't say I am happy with how the code turned out , and would be into suggestions to make things cleaner. However, it does solve the issue

**Comment by alexcrichton** [comment]
Hey @posix4e, I'm taking over the curl crate for now and I've got an API rewrite over at https://github.com/alexcrichton/curl-rust/pull/105 which I believe should address this as well. If you'd like to take a look though feel free! 

I hope to soon get around to #74 and bind the multi API but we'll take some baby steps first!

**Comment by posix4e** [comment]
Very good sir!

On Thu, May 12, 2016 at 10:21 AM Alex Crichton <notifications@github.com>
wrote:

> Hey @posix4e <https://github.com/posix4e>, I'm taking over the curl crate
> for now and I've got an API rewrite over at #105
> <https://github.com/alexcrichton/curl-rust/pull/105> which I believe
> should address this as well. If you'd like to take a look though feel free!
>
> I hope to soon get around to #74
> <https://github.com/alexcrichton/curl-rust/pull/74> and bind the multi
> API but we'll take some baby steps first!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/alexcrichton/curl-rust/pull/75#issuecomment-218826068>
>
-- 
Sent from my mobile 4045076749
Alex Newman

**Pull request closed without merging**
