### PR TITLE
Add a `protocol-ftp` feature which enables FTP support when using bundled libcurl (#322)

### LINKED ISSUE #322: Enable FTP protocol support in bundled libcurl
Could we enable FTP support when building the bundled curl version, or at least support it via feature flag?

### PR DESCRIPTION
**Pull request by ebarnard**
Closes #322

### CODE REVIEW

**Comment by alexcrichton** [comment]
Awesome, thanks!

**Comment by ebarnard** [comment]
@alexcrichton Would it be possible to get a release with this change?

**Comment by alexcrichton** [comment]
Sure thing, done now!

**Comment by ebarnard** [comment]
Thanks

**Pull request merged**
