### PR TITLE
feat: add three more curl multi options

### PR DESCRIPTION
**Pull request by weihanglo**
- [`CURLMOPT_MAX_CONCURRENT_STREAMS`](https://curl.se/libcurl/c/CURLMOPT_MAX_CONCURRENT_STREAMS.html): Added in 7.67.0 
- [`CURLMOPT_PUSHFUNCTION`](https://curl.se/libcurl/c/CURLMOPT_PUSHFUNCTION.html): Added in 7.44.0 
- [`CURLMOPT_PUSHDATA`](https://curl.se/libcurl/c/CURLMOPT_PUSHDATA.html): Added in 7.44.0 

However, server push is a bit hard to provide a sane API. Leave them for people needing it in the future.

### CODE REVIEW

**Comment by weihanglo** [comment]
system curl is stuck in 7.47.0. Does that mean this PR points to nowhere?

**Comment by ehuss** [comment]
> system curl is stuck in 7.47.0. Does that mean this PR points to nowhere?

In systest/build.rs, there are version-specific checks that you can add exceptions for older versions.

**Comment by weihanglo** [comment]
Thanks! Fixed with 3cbc959d562d6b130da2ca80db4ca37f9123c7d5

**Comment by alexcrichton** [comment]
👍

**Pull request merged**
