### PR TITLE
Add support for configuring DNS servers

### PR DESCRIPTION
**Pull request by thijsc**
Disabled feature by default because this only works when curl is linked with `c-ares`.

### CODE REVIEW

**Comment by sagebind** [comment]
Indeed, it looks like curl just returns `CURLE_NOT_BUILT_IN` if the configured DNS backend doesn't support it:

https://github.com/curl/curl/blob/master/lib/hostsyn.c#L59-L69

**Comment by thijsc** [comment]
Correct, it gives an error:

```
A requested feature, protocol or option was not found built-in in this libcurl due to a build-time decision.
```

I've removed the feature and tweaked the doc comment a bit to make the requirement to use this more clear.

**Comment by alexcrichton** [comment]
👍

**Comment by thijsc** [comment]
Would you mind bumping the crate version so we can use this?

**Comment by alexcrichton** [comment]
Sure thing, should be published now

**Pull request merged**
