### PR TITLE
Use cargo: (universally supported) instead of cargo:: (1.80+ only) syntax for rustc-check-cfg

### LINKED ISSUE #576: error: unsupported output in build script of `curl-sys v0.4.76+curl-8.10.1`: `cargo::rustc-check-cfg=cfg(libcurl_vendored,link_libnghttp2,link_libz,link_openssl,)`
#575 accidentally increased the (undocumented) MSRV to 1.80, and older rust versions fail to compile.

### PR DESCRIPTION
**Pull request by nabijaczleweli**
Ref: #575
Closes #576
Closes https://github.com/nabijaczleweli/cargo-update/issues/277
Supplants #577

### CODE REVIEW

**Comment by nabijaczleweli** [comment]
CI failure unrelated :v

**Comment by alexcrichton** [comment]
As-is the case with https://github.com/alexcrichton/curl-rust/pull/577, can you add CI here for the version that you're interested in?

**Comment by alexcrichton** [comment]
Thanks! I think the CI failure is the need to update [this line too](https://github.com/alexcrichton/curl-rust/blob/a09b66e0f2e84843e1f6b58dc349f0c40dd18fd3/curl-sys/build.rs#L9)?

**Comment by nabijaczleweli** [comment]
Survey says: no (but I did update that too, thanks).

I wanna say that if you trigger a build on trunk it will happen too? This smells like a mirror issue (if I repeat the failing curl locally I get a valid gzip stream).

**Comment by nabijaczleweli** [comment]
Actually no, I wgetted it :skull: `curl https://www.openssl.org/source/old/1.0.2/openssl-1.0.2g.tar.gz | tar tzf -` does fail.

perl curl -v this just wants -L: 
```
< HTTP/2 301
< content-type: text/html
< location: https://github.com/openssl/openssl/releases/download/OpenSSL_1_0_2g/openssl-1.0.2g.tar.gz
< x-cloud-trace-context: 6bbbe5a1d38426fd969f050d7e9dd009
< date: Mon, 30 Sep 2024 18:14:55 GMT
< server: Google Frontend
< content-length: 169
< via: 1.1 google
< strict-transport-security: max-age=31536000; includeSubDomains; preload
```

**Comment by nabijaczleweli** [comment]
yup, that fixed it. and the 1.75 job works too

**Pull request merged**
