### PR TITLE
Exposed the CURLOPT_UPLOAD_BUFFERSIZE curl option.

### PR DESCRIPTION
**Pull request by darkprokoba**
See also: https://curl.se/libcurl/c/CURLOPT_UPLOAD_BUFFERSIZE.html

### CODE REVIEW

**Comment by alexcrichton** [comment]
Looks good but I believe there's some CI errors.

**Comment by darkprokoba** [comment]
> CI / Test (system-curl) (pull_request) Failing after 2m — Test (system-curl) 
I guess this CI test uses libcurl earlier than 7.62.0...
Perhaps in the test at tests/easy.rs:303 I could check the libcurl version and skip the h.upload_buffer_size(10) call?
Not sure how to go about this :-)

**Comment by alexcrichton** [comment]
Conditionally testing the version is fine, but it looks like you'll also need to update `systest/build.rs` with conditionally checking the constant itself.

**Comment by darkprokoba** [comment]
> All checks have passed

Whew :-)

**Pull request merged**
