### PR TITLE
An example of curl_multi

### PR DESCRIPTION
**Pull request by posix4e**
I'm looking at adding support for the curl_multi api. This creates a lot of duplication (which I have tried to avoid) and most likely we will need a different library that pulls in eventual and mio to actually make use of the bindings. I'm working on one called micro-hyper. Consider this pull a demonstration and a WIP. The question I have is what the api should look like.

### CODE REVIEW

**Comment by carllerche** [comment]
Sorry for the delay. Trying to catch up.

I definitely want to get curl multi bound. Glancing through the PR though, it looks like there is a lot of duplication. Any way to try to avoid duplicating definitions?

**Comment by posix4e** [comment]
No worries. Notice CurlM vs Curl for a lot of the options. What dups are you most worried about?

**Comment by carllerche** [comment]
It's a bit hard for me to follow (and I have lost a lot of context), but I'm noticing some duplication like `CURL_VERSION_IPV6`.

**Comment by posix4e** [comment]
So i removed the easy.rs file altogether.  Is this any clearer?

**Comment by alexcrichton** [comment]
Ok, I've started binding the multi interface in https://github.com/alexcrichton/curl-rust/pull/109, so I'm gonna close this now. Sorry for the delayed response :)

**Pull request closed without merging**
