### PR TITLE
Enable support of  scope ID for IPv6 link local addresses

### PR DESCRIPTION
**Pull request by M-Tarasov**
Try to resolve issue https://github.com/alexcrichton/curl-rust/issues/568

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! Is it possible to add a test for this?

**Comment by M-Tarasov** [comment]
> Thanks! Is it possible to add a test for this?

Unfortunately, I have no idea how it could be tested with unit tests: from `rust` point of view, it just on more define in build script for a C library, from the other side, the effect of this define could be observed deep in the `libcurl` library itself. It is possible, to test it in an integration test within specific environment, but it would require much effort to set up. I could just say, that this change is working for my project.

**Comment by alexcrichton** [comment]
Does connecting with ipv6 not work at all without this? Or could a dummy server be set up with a different link-local ID and then curl tries to connect to it and it would fail if this isn't supported?

**Comment by M-Tarasov** [comment]
> Does connecting with ipv6 not work at all without this? Or could a dummy server be set up with a different link-local ID and then curl tries to connect to it and it would fail if this isn't supported?

The issue is related to the IPv6 link-local addresses (all addresses within `fe80::/10` range) only. 

Just one example: let suppose you have a local web server running with `python3 -m http.server -b "::" 8123`. Your `eth0` interface has a link local IPv6 address `fe80::c4:d164:150d:282c`. Then you make standard curl calls like this:

```bash
curl http://[fe80::c4:d164:150d:282c%eth0]:8123  # works fine, with scope id eth0
curl http://[fe80::c4:d164:150d:282c]:8123       # will not work without scope id
```
Without the flag (`HAVE_SOCKADDR_IN6_SIN6_SCOPE_ID`) enabled, both variants would fail.

In the `libcurl` itself, the `HAVE_SOCKADDR_IN6_SIN6_SCOPE_ID` flag is defined whenever the system's `struct sockaddr_in6` has the field `sin6_scope_id` (no idea, where it could be missing, maybe some very old systems). See curl's original `CMakeLists.txt`: https://github.com/curl/curl/blob/curl-8_9_0/CMakeLists.txt#L291

**Pull request merged**
